version: "3.5"

services:
  django:
    build: .
    depends_on:
      - postgres
    env_file:
      - envs/django
      - envs/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/srv
  postgres:
    env_file:
      - envs/postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
